import type { ResearchApiProtocol, ResearchAuthMode, ResearchProviderPreset } from "./types";

export type ResearchProviderGroup = "domestic" | "international" | "local" | "custom";

export interface ResearchProviderPresetDefinition {
  id: ResearchProviderPreset;
  label: string;
  labelEn: string;
  endpoint: string;
  protocol: ResearchApiProtocol;
  authMode: ResearchAuthMode;
  authHeaderName?: string;
  authHeaderPrefix?: string;
  defaultName: string;
  defaultNameEn: string;
  group: ResearchProviderGroup;
  note?: string;
  noteEn?: string;
}

export const RESEARCH_PROVIDER_PRESETS: ResearchProviderPresetDefinition[] = [
  {
    id: "volcengine_ark",
    label: "火山方舟 API",
    labelEn: "Volcengine Ark",
    endpoint: "https://ark.cn-beijing.volces.com/api/v3",
    protocol: "responses",
    authMode: "bearer",
    defaultName: "火山方舟",
    defaultNameEn: "Volcengine Ark",
    group: "domestic",
    note: "普通方舟推理请填写模型 Endpoint ID（ep- 开头）或控制台支持的模型 ID。",
    noteEn: "Use an Ark endpoint ID (ep-...) or a model ID supported by your console.",
  },
  {
    id: "volcengine_agent_plan",
    label: "方舟 Agent Plan",
    labelEn: "Ark Agent Plan",
    endpoint: "https://ark.cn-beijing.volces.com/api/plan/v3",
    protocol: "responses",
    authMode: "bearer",
    defaultName: "Agent Plan",
    defaultNameEn: "Agent Plan",
    group: "domestic",
    note: "必须使用 Agent Plan 专用 API Key 和套餐支持的模型名；它与普通方舟 Key 不通用。",
    noteEn: "Requires an Agent Plan API key and a model included in that plan; standard Ark keys are different.",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    labelEn: "DeepSeek",
    endpoint: "https://api.deepseek.com",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "DeepSeek",
    defaultNameEn: "DeepSeek",
    group: "domestic",
  },
  {
    id: "alibaba_qwen",
    label: "阿里云百炼 / 通义千问",
    labelEn: "Alibaba Qwen",
    endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "阿里云百炼",
    defaultNameEn: "Alibaba Qwen",
    group: "domestic",
    note: "预设为华北 2（北京）按量付费域名；其他地域或套餐请替换 Base URL。",
    noteEn: "Preset uses the Beijing pay-as-you-go domain. Replace the Base URL for another region or plan.",
  },
  {
    id: "zhipu",
    label: "智谱 GLM",
    labelEn: "Zhipu GLM",
    endpoint: "https://open.bigmodel.cn/api/paas/v4",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "智谱 GLM",
    defaultNameEn: "Zhipu GLM",
    group: "domestic",
  },
  {
    id: "moonshot",
    label: "Moonshot / Kimi",
    labelEn: "Moonshot / Kimi",
    endpoint: "https://api.moonshot.cn/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "Moonshot Kimi",
    defaultNameEn: "Moonshot Kimi",
    group: "domestic",
  },
  {
    id: "minimax",
    label: "MiniMax（Anthropic 兼容）",
    labelEn: "MiniMax (Anthropic-compatible)",
    endpoint: "https://api.minimaxi.com/anthropic",
    protocol: "anthropic_messages",
    authMode: "x_api_key",
    defaultName: "MiniMax",
    defaultNameEn: "MiniMax",
    group: "domestic",
    note: "使用 MiniMax 的 Anthropic 兼容接口，支持 Claude Code 类工具常用的 Messages 协议。",
    noteEn: "Uses MiniMax's Anthropic-compatible Messages API, also used by Claude Code-style tools.",
  },
  {
    id: "siliconflow",
    label: "SiliconFlow 硅基流动",
    labelEn: "SiliconFlow",
    endpoint: "https://api.siliconflow.cn/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "SiliconFlow",
    defaultNameEn: "SiliconFlow",
    group: "domestic",
  },
  {
    id: "openai",
    label: "OpenAI",
    labelEn: "OpenAI",
    endpoint: "https://api.openai.com/v1",
    protocol: "responses",
    authMode: "bearer",
    defaultName: "OpenAI",
    defaultNameEn: "OpenAI",
    group: "international",
  },
  {
    id: "anthropic",
    label: "Anthropic Claude（CC）",
    labelEn: "Anthropic Claude (CC)",
    endpoint: "https://api.anthropic.com/v1",
    protocol: "anthropic_messages",
    authMode: "x_api_key",
    defaultName: "Anthropic Claude",
    defaultNameEn: "Anthropic Claude",
    group: "international",
    note: "使用 Claude Messages API。这里需要 Anthropic API Key；Claude Code 订阅登录不能直接当作 API Key。",
    noteEn: "Uses the Claude Messages API. An Anthropic API key is required; a Claude Code subscription login is not an API key.",
  },
  {
    id: "xai",
    label: "xAI Grok",
    labelEn: "xAI Grok",
    endpoint: "https://api.x.ai/v1",
    protocol: "responses",
    authMode: "bearer",
    defaultName: "xAI Grok",
    defaultNameEn: "xAI Grok",
    group: "international",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    labelEn: "OpenRouter",
    endpoint: "https://openrouter.ai/api/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "OpenRouter",
    defaultNameEn: "OpenRouter",
    group: "international",
  },
  {
    id: "google_gemini",
    label: "Google Gemini",
    labelEn: "Google Gemini",
    endpoint: "https://generativelanguage.googleapis.com/v1beta",
    protocol: "gemini_native",
    authMode: "x_google_api_key",
    defaultName: "Google Gemini",
    defaultNameEn: "Google Gemini",
    group: "international",
    note: "使用 Gemini 原生 generateContent 协议与 x-goog-api-key 鉴权。",
    noteEn: "Uses Gemini's native generateContent protocol with x-goog-api-key authentication.",
  },
  {
    id: "groq",
    label: "Groq",
    labelEn: "Groq",
    endpoint: "https://api.groq.com/openai/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "Groq",
    defaultNameEn: "Groq",
    group: "international",
  },
  {
    id: "mistral",
    label: "Mistral AI",
    labelEn: "Mistral AI",
    endpoint: "https://api.mistral.ai/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "Mistral AI",
    defaultNameEn: "Mistral AI",
    group: "international",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    labelEn: "Perplexity",
    endpoint: "https://api.perplexity.ai/v1",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "Perplexity",
    defaultNameEn: "Perplexity",
    group: "international",
    note: "使用 Sonar API；联网结果会解析 citations 与 search_results。",
    noteEn: "Uses the Sonar API and parses citations plus search_results.",
  },
  {
    id: "ollama",
    label: "Ollama（本地）",
    labelEn: "Ollama (local)",
    endpoint: "http://localhost:11434",
    protocol: "ollama_chat",
    authMode: "none",
    defaultName: "Ollama",
    defaultNameEn: "Ollama",
    group: "local",
    note: "无需 API Key。请先启动 Ollama，并允许扩展访问 localhost。",
    noteEn: "No API key is required. Start Ollama first and allow the extension to access localhost.",
  },
  {
    id: "lm_studio",
    label: "LM Studio（本地）",
    labelEn: "LM Studio (local)",
    endpoint: "http://localhost:1234/v1",
    protocol: "chat_completions",
    authMode: "none",
    defaultName: "LM Studio",
    defaultNameEn: "LM Studio",
    group: "local",
    note: "预设使用 OpenAI 兼容端点；若 LM Studio 启用了 API Token，请把鉴权改为 Bearer Token。",
    noteEn: "Uses the OpenAI-compatible endpoint. Switch auth to Bearer Token if LM Studio API tokens are enabled.",
  },
  {
    id: "custom",
    label: "自定义模型服务",
    labelEn: "Custom model service",
    endpoint: "",
    protocol: "chat_completions",
    authMode: "bearer",
    defaultName: "自定义 API",
    defaultNameEn: "Custom API",
    group: "custom",
    note: "可独立选择 OpenAI Chat、Responses、Anthropic Messages、Gemini 原生或 Ollama 协议，以及对应鉴权方式。",
    noteEn: "Choose OpenAI Chat, Responses, Anthropic Messages, native Gemini, or Ollama plus the matching auth method.",
  },
];

export const RESEARCH_PROVIDER_PRESET_MAP = Object.fromEntries(
  RESEARCH_PROVIDER_PRESETS.map((preset) => [preset.id, preset]),
) as Record<ResearchProviderPreset, ResearchProviderPresetDefinition>;
